
DECLARE @RUN_TYPE AS VARCHAR(10);
DECLARE @WEEK as Date;
Set @RUN_TYPE = dbo.DSGetCDPRunType(getDate());
Set @WEEK = dbo.DSGetPriorMonday(getDate());
--Set @RUN_TYPE = 'RAW';
--Set @WEEK = '2022-03-21';

SELECT [SKU_10D]
      ,[LOCATION]
      ,[FISCAL_MONTH]
      ,[FISCAL_YEAR]
      ,[MARKET]
      ,[RUN_TYPE]
      ,[CYCLE]
      ,[DEMAND_PRIORITY_12D]

      ,SUM([MATERIAL_CAPACITY_CONSTRAINTS]) AS MATERIAL_CAPACITY_CONSTRAINTS
      ,SUM([MATERIAL_LEADTIME_CONSTRAINTS]) AS MATERIAL_LEADTIME_CONSTRAINTS
      ,SUM([MATERIAL_BROKEN_NETWORK_CONSTRAINTS]) AS MATERIAL_BROKEN_NETWORK_CONSTRAINTS
      ,SUM([MASS_CAPACITY_SHORTAGE]) AS MASS_CAPACITY_SHORTAGE
      ,SUM([FPA_CAPACITY_SHORTAGE]) AS FPA_CAPACITY_SHORTAGE
      ,SUM([FROZEN_WINDOW_CONSTRAINTS]) AS FROZEN_WINDOW_CONSTRAINTS
      ,SUM([LEADTIME_BEFORE_CURRENT_CONSTRAINTS]) AS LEADTIME_BEFORE_CURRENT_CONSTRAINTS
      ,SUM([PLANNING_CALENDAR_CONSTRAINTS]) AS PLANNING_CALENDAR_CONSTRAINTS
      ,SUM([EFFECTIVITY_CONSTRAINTS]) AS EFFECTIVITY_CONSTRAINTS
      ,SUM([BROKEN_NETWORK_CONSTRAINTS]) AS BROKEN_NETWORK_CONSTRAINTS

  FROM [SC_PLN_DS].[SUPPLY_COMMIT].[STG_PBI_RESULT]
  WHERE [CYCLE] = @WEEK
  AND RUN_TYPE = @RUN_TYPE

GROUP BY

[SKU_10D]
      ,[LOCATION]
      ,[FISCAL_MONTH]
      ,[FISCAL_YEAR]
      ,[MARKET]
      ,[RUN_TYPE]
      ,[CYCLE]
      ,[DEMAND_PRIORITY_12D]